[package]
name = "webserver"
version = "0.1.0"
authors = ["Stefan van den Berg <bergshm@gmail.com>"]

[dependencies]
clap = "2.32.0"
hyper = "0.12"
job_scheduler = "1.0.5"
serde_json = "1.0.32"
lettre = "0.8"
lettre_email = "0.8"
native-tls = "0.1"
