name: webserver
version: git
summary: webserver for hello world
description: |
  Returns hello world on the port specified from the cla.

confinement: devmode

apps:
  webserver:
    command: webserver --ip 192.168.1.230:8090
    daemon: simple
    restart-condition: always
    plugs:
        - network
        - network-bind

parts:
  webserver:
    source: .
    plugin: rust
    build-attributes: [no-system-libraries]
    build-packages:
    - libudev-dev
    - libssl-dev
    - make
    - pkg-config
    stage-packages:
    - libssl1.0.0
    - libudev1
    - libstdc++6
